# This file allows easier configurations and overrides for individual nodes in carma-messenger
# Package and node structure example is provided as a commented out code
# Any parameters here will override the default parameters in the respective package's yaml files
# For brevity the parameter descriptions are not provided here. The descriptions are located
# in each package's parameters yaml file
# Only the parameters that need to be overridden should be included in this file, rest will
# use the default values in the respective package's yaml files
# NOTE: Be sure to include the node name here, which may not be same as the package name

hardware_interface:
  v2x_ros_driver_node:
    ros__parameters:
      v2x_radio_address: "192.168.0.40"

# # Other general examples:
# traffic_incident:
#   ros__parameters:
#     down_track: 50.0
#     event_reason: 'MOVE OVER LAW'
#     event_type: 'CLOSED'
#     geofence_start_end_data_timeout: 
#     min_gap: 4.0
#     sender_id: 'USDOT-49096'
#     up_track: 50.0

# emergency_response_vehicle_plugin_node:
#   ros__parameters: 
#     bsm_generation_frequency: 10.0
#     bsm_message_id: 8
#     emergency_route_file_name: "DEFAULT-FILE-NAME.csv"
#     enable_emergency_response_vehicle_plugin: false
#     listening_port: 5005
#     min_distance_to_next_destination_point: 30.0 
#     route_file_folder: "/opt/carma/vehicle/routes"


